### PR TITLE
orange frame alignment fix: default, aligncenter. Padding added align…

### PR DESCRIPTION
**Pull request by spworky**
…left, alignright. Right frame added to alignright.

This includes fix for Theme Issue #17

### CODE REVIEW

**Review by pikemurdy — CHANGES_REQUESTED** [review]
Need to adjust for an image with a caption. Align right and align left are fine. But align center, the caption goes off to the right in an odd way.

**Comment by spworky** [comment]
Sorry – just now seeing this comment. I will work on getting that fixed.

**Comment by spworky** [comment]
Fixed caption issues at full size, medium, and thumbnail image sizes
– added character limit for captions. 
– caption aligns to the same direction as the floated frame
– center align at mobile widths has caption underneath; to the right at wider sizes

**Review by pikemurdy — APPROVED** [review]
With long captions and small images, there's still some weirdness. But looking at how all this works, I think it's mostly edge cases that will break it. Let's merge this for now.

**Pull request merged**
