### PR TITLE
Button on dark

### PR DESCRIPTION
**Pull request by spworky**

### CODE REVIEW

**Review by pikemurdy — CHANGES_REQUESTED** [review]
This works, but I wonder if we can kill two birds with one stone on this. And fix the nested colors issue.

The color of the type works, but not the links. I'm wondering if we need to hook the link colors to text-dark. Something like:

.text-dark a {
  color: $utlink:
}
Not sure if that would work, but let's see if we can just get that working.


Screen Shot 2022-04-28 at 3 20 48 PM

**Comment by spworky** [comment]
@pikemurdy So, to make sure I am following – you are looking at changing the other style of buttons as well and not just the link-text – is that right?

**Comment by pikemurdy** [comment]
Yeah, if you look at the screenshot. When you create a dark content-strip, and put in a light card, the text goes dark. But none of the links. The links stay white, making them hard to read.

**Comment by spworky** [comment]
@pikemurdy Take a look at this branch when you get a chance. I think I have this working pretty well now.

**Review by pikemurdy — APPROVED** [review]

**Pull request merged**
